export const videoLibrary = [
    {
        id: 1,
        chanelName: "YUSUF",
        chanelPhoto: "https://yt3.ggpht.com/ytc/AIdro_kIoZ3-DQvRa6dldy2-746ygS1CbQMxkaZJp85EVMbzEkY=s88-c-k-c0x00ffffff-no-rj",
        videoName: "6 Ayda PARA Kazanan Bir Oyun Geliştiricisi Nasıl Olunur ?",
        videoPhoto: "https://i.ytimg.com/vi/katAc4yzl3w/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAMuRWsqA-CIsIOHEPrHP1XwtFH1w",
        date: "2 hafta önce",
        videoType: "Education",
        videoTime: "9:10",
        videoLink: `<iframe width="853" height="480" src="https://www.youtube.com/embed/katAc4yzl3w" title="6 Ayda PARA Kazanan Bir Oyun Geliştiricisi Nasıl Olunur ?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
        viewCount: "11 Bin",
    },
    {
        id: 2,
        chanelName: "Arabesk Desing",
        chanelPhoto: "https://yt3.ggpht.com/Eg9W12El9gK9G_fpohXrO4PTyPmLSkk-KwQJYJ4O0gymPgcN1TBte4J-t5s10nGhZO-RxPUDT34=s88-c-k-c0x00ffffff-no-nd-rj",
        videoName: "Gülden Karaböcek ft Taladro - Ben Olmalıydım (Mix)",
        videoPhoto: "https://i.ytimg.com/vi/VeLgNdDw7DY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD56rE2wTYLylnfCL7c8EVce12lWQ",
        date: "1 yıl önce",
        videoType: "music",
        videoTime: "5:24",
        videoLink: `<iframe width="853" height="480" src="https://www.youtube.com/embed/VeLgNdDw7DY" title="Gülden Karaböcek ft Taladro - Ben Olmalıydım (Mix) #ilkgündenaşıktımsana" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen> </iframe>`,
        viewCount: "6 Milyon",
    },

    {
        id: 3,
        chanelName: "Chill Cities Vibes",
        chanelPhoto: "https://yt3.ggpht.com/zyPKHdHDhVwOmndY9ByT3ndJ7OkaHcLa-Ols7HijCo7FG4XEQefJqvwYC3Te1yTlCVxbTIlh=s88-c-k-c0x00ffffff-no-rj",
        videoName: "Late Night Vibes 🌜 Lofi Chill Night 🌆 Beats To Chill / Relax",
        videoPhoto: "https://i.ytimg.com/vi/-b408aTi_k8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCinPUSmWXGzjXuCFPmWWcb4V_tKw",
        date: "2 hafta önce",
        videoType: "Music",
        videoTime: "11:54:56",
        videoLink: `<iframe width="853" height="480" src="https://www.youtube.com/embed/-b408aTi_k8" title="Late Night Vibes 🌜 Lofi Chill Night 🌆 Beats To Chill / Relax" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
        viewCount: 14.000,
    },
    
    {
        id: 4,
        chanelName: "AsmrProg",
        chanelPhoto: "https://yt3.ggpht.com/DnF7_67_DOyb5d7O0YPF94SLvLYIn6sAodWonN2BnfVHnFPQKS41qNetPkugplbEGP6g3cRRl5I=s68-c-k-c0x00ffffff-no-rj",
        videoName: "ASMR Programming - Complete Responsive Portfolio Design - No Talking",
        videoPhoto: "https://i.ytimg.com/vi/womd8BFIbDY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAcwiQm0LYTM7bgvEEJqxUnISbntA",
        date: "7 ay önce",
        videoType: "Software",
        videoTime: "43:39",
        videoLink: `<iframe width="853" height="480" src="https://www.youtube.com/embed/womd8BFIbDY" title="ASMR Programming - Complete Responsive Portfolio Design - No Talking" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
        viewCount: 341.000,
    },
    {
        id: 5,
        chanelName: "Çimen Show",
        chanelPhoto: "https://yt3.ggpht.com/0_LgKotf6BPhA9LR3_8l5hyvw8GU_1kt9mLlMQ1MOUg5hmhXkRZGSuJUEbwYa-1aNqNds2mLig=s88-c-k-c0x00ffffff-no-rj",
        videoName: "Cem İşçiler & Fazlı Polat Çimen Show 2. Sezon 25. Bölüm - Konuk: Ayşe Balıbey",
        videoPhoto: "https://i.ytimg.com/vi/0NPetm0WDdw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCR_UKdQut2dFFuUTzB1pfxtqX7JQ",
        date: "2 yıl önce",
        videoType: "Komedi",
        videoTime: "57:40",
        videoLink: `<iframe width="853" height="480" src="https://www.youtube.com/embed/0NPetm0WDdw" title="Cem İşçiler &amp; Fazlı Polat Çimen Show 2. Sezon 25. Bölüm - Konuk: Ayşe Balıbey" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
        viewCount: 788.000,
    },
    {
        id: 6,
        chanelName: "Sabo Satranç",
        chanelPhoto: "https://yt3.ggpht.com/Hf9Jc5PDXrwBlKzZCGxgcnm2biA25AkE6CJh_pDdTn-XQsv0U-Y2Yul83PWkl73NdHcGwJvG3w=s68-c-k-c0x00ffffff-no-rj",
        videoName: "Alireza Firouzja İNANILMAZ OYNADI Nepomniachtchi KURTARABİLİR Mİ? | Adaylar Turnuvası",
        videoPhoto: "https://i.ytimg.com/vi/lY3rkRKmJEc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCt7gwqtptVJMqDuIIq8ULZNzJAxw",
        date: "2 gün önce",
        videoType: "Game",
        videoTime: "14:52",
        videoLink: `<iframe width="702" height="395" src="https://www.youtube.com/embed/lY3rkRKmJEc" title="Alireza Firouzja İNANILMAZ OYNADI Nepomniachtchi KURTARABİLİR Mİ? | Adaylar Turnuvası" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`,
        viewCount: 23.000,
    },
    /*
    {
        id: ,
        chanelName: "",
        chanelPhoto: "",
        videoName: "",
        videoPhoto: "",
        date: "",
        videoType: "",
        videoTime: ,
        videoLink: ``,
        viewCount: ,
    },
    */
]